apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-zone-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-zone-api
  template:
    metadata:
      labels:
        app: k8s-zone-api
    spec:
      serviceAccountName: k8s-zone-reader
      containers:
      - name: k8s-zone-api
        image: library/infofetch:1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: k8s-api-access
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: k8s-api-access
        projected:
          sources:
          - serviceAccountToken:
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-zone-api
spec:
  selector:
    app: k8s-zone-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-zone-reader
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-zone-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-zone-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-zone-reader
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-zone-role
  apiGroup: rbac.authorization.k8s.io