apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zone-virtualservice
spec:
  hosts:
    - "*"  # Match all hosts
  gateways:
    - services/services-gateway
    - services/customer-admin-gateway
  http:
    - match:
        - uri:
            prefix: /zones

      route:
        - destination:
            host: rrs-api  # Route to the Service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /critical-pods
      route:
        - destination:
            host: rrs-api  # Route to the Service
            port:
              number: 8080