openapi: 3.0.0
info:
  title: Kubernetes Node Zone API
  description: API to fetch information about Kubernetes nodes grouped by zone
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /zones:
    get:
      summary: Retrieve Kubernetes nodes grouped by their zones
      operationId: getZones
      responses:
        '200':
          description: A list of nodes grouped by their zones
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                      roles:
                        type: string
                      age:
                        type: string
                      version:
                        type: string
                      cpu:
                        type: string
                      memory:
                        type: string
        '404':
          description: Endpoint not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Not Found"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
